import { app, BrowserWindow, dialog, ipcMain } from 'electron';
import path from 'node:path';
import fs from 'fs';
import AppDatabase from './Database/database';
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

let database: AppDatabase;

/** openedDirectory | openedWorkspace; TODO: consider making single object with bool 'isWorkspace' */
let openedDirectory = null;
/** openedDirectory | openedWorkspace; TODO: consider making single object with bool 'isWorkspace'  */
let openedWorkspace = null;
let workspaceDirectories = null;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

const createWindow = (): void => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: 600,
    width: 800,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
    autoHideMenuBar: true,
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Open the DevTools.
  //mainWindow.webContents.openDevTools();

  // Handle the request from the renderer process
	ipcMain.handle('choose-directory', chooseDirectory);
	ipcMain.handle('choose-workspace', chooseWorkspace);
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', () => {
  database = new AppDatabase();
  createWindow();
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.

async function chooseDirectory (event: any) {
	const result = await dialog.showOpenDialog({ properties: ['openDirectory'] });
	if (result.canceled) {
		return { basename: '', openedDirectory: '', canceled: result.canceled };
	}

	openedDirectory = result.filePaths[0];
	openedWorkspace = null;
	workspaceDirectories = null;

	let filename = path.basename(openedDirectory);
	let id = database.addAbsolutePath(openedDirectory, filename);

	//if (!languageServer) {
	//	MAIN_initializeLanguageServer();
	//}

	return { basename: filename, openedDirectory: openedDirectory, id: id, canceled: result.canceled };
}

async function chooseWorkspace(event: any) {
	const result = await dialog.showOpenDialog({ properties: ['openFile'] });
	if (result.canceled) {
		return {
			workspaceFileAbsolutePath: null,
			workspaceFileNameWithoutExtension: null,
			directories: [],
			canceled: result.canceled };
	}

	openedDirectory = null;
	openedWorkspace = result.filePaths[0];
	workspaceDirectories = null;

	let filename = path.basename(openedWorkspace);
	let id = database.addAbsolutePath(openedWorkspace, filename);

	let fileContent = fs.readFileSync(openedWorkspace, 'utf8');
	let jsonObject = JSON.parse(fileContent);

	if (!jsonObject.folders) {
		throw new Error('if (!jsonObject.folders)');
	}

	let parentDirectoryAbsolutePath = path.dirname(openedWorkspace);

	let directories = [];
	  
	for (let i = 0; i < jsonObject.folders.length; i++) {
		let folderEntry = jsonObject.folders[i];
		let absolutePath = path.join(parentDirectoryAbsolutePath, folderEntry.path);
		let filename = path.basename(absolutePath);
		let id = database.addAbsolutePath(absolutePath, filename);
		directories.push({
			basename: filename,
			absolutePath: absolutePath,
			id: id,
		});
	}

	workspaceDirectories = directories;

	//if (!languageServer) {
	//	MAIN_initializeLanguageServer();
	//}

	return {
		workspaceFileAbsolutePath: openedWorkspace,
		workspaceFileNameWithoutExtension: path.parse(openedWorkspace).name,
		directories: directories,
		canceled: result.canceled
	};
}
