import { app, BrowserWindow, dialog, ipcMain } from 'electron';
import path from 'node:path';
import fs from 'fs';
import { AppDatabase } from './Database/database';
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

let database: AppDatabase;

/** openedDirectory | openedWorkspace; TODO: consider making single object with bool 'isWorkspace' */
let openedDirectory: string | null = null;
/** openedDirectory | openedWorkspace; TODO: consider making single object with bool 'isWorkspace'  */
let openedWorkspace: string | null = null;
let workspaceDirectories = null;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

const createWindow = (): void => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: 600,
    width: 800,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
    autoHideMenuBar: true,
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Open the DevTools.
  //mainWindow.webContents.openDevTools();

  // Handle the request from the renderer process
	ipcMain.handle('choose-directory', chooseDirectory);
	ipcMain.handle('choose-workspace', chooseWorkspace);
	ipcMain.handle('get-filesystem-entries', getFilesystemEntries);
	ipcMain.handle('get-filesystem-entry-by-id', getFilesystemEntryById);
	ipcMain.handle('get-filesystem-entry-by-id-array', getFilesystemEntryById_ARRAY);
	ipcMain.handle('editor-read-all-text', editorReadAllText);
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', () => {
  database = new AppDatabase();
  createWindow();
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.

/**
 * TODO: Store the path more optimally to avoid doing this each time?
 * TODO: capital 'c' or lowercase, encoded ':' and etc... or not?
 */
function formatAbsolutePath(absolutePath: string) {
	return 'file:///' + absolutePath.replaceAll('\\', '/');
}

/**
 * @param {*} absolutePath 
 * @returns {boolean} to indicate whether the invoker is permitted to continue execution with the given absolutePath
 */
function isValidAbsolutePath(absolutePath: string) {
    // The provided absolute file path is validated.
    // If the absolute file path is NOT recognized, then an empty enumeration is returned.
    if (absolutePath !== openedDirectory && !database.contains(absolutePath)) return false;

	return true;
}

async function chooseDirectory (event: any) {
	const result = await dialog.showOpenDialog({ properties: ['openDirectory'] });
	if (result.canceled) {
		return { basename: '', openedDirectory: '', canceled: result.canceled };
	}

	openedDirectory = result.filePaths[0];
	openedWorkspace = null;
	workspaceDirectories = null;

	let filename = path.basename(openedDirectory);
	let id = database.addAbsolutePath(openedDirectory, filename);

	//if (!languageServer) {
	//	MAIN_initializeLanguageServer();
	//}

	return { basename: filename, openedDirectory: openedDirectory, id: id, canceled: result.canceled };
}

async function chooseWorkspace(event: any) {
	const result = await dialog.showOpenDialog({ properties: ['openFile'] });
	if (result.canceled) {
		return {
			workspaceFileAbsolutePath: null,
			workspaceFileNameWithoutExtension: null,
			directories: [],
			canceled: result.canceled };
	}

	openedDirectory = null;
	openedWorkspace = result.filePaths[0];
	workspaceDirectories = null;

	let filename = path.basename(openedWorkspace);
	let id = database.addAbsolutePath(openedWorkspace, filename);

	let fileContent = fs.readFileSync(openedWorkspace, 'utf8');
	let jsonObject = JSON.parse(fileContent);

	if (!jsonObject.folders) {
		throw new Error('if (!jsonObject.folders)');
	}

	let parentDirectoryAbsolutePath = path.dirname(openedWorkspace);

	let directories = [];
	  
	for (let i = 0; i < jsonObject.folders.length; i++) {
		let folderEntry = jsonObject.folders[i];
		let absolutePath = path.join(parentDirectoryAbsolutePath, folderEntry.path);
		let filename = path.basename(absolutePath);
		let id = database.addAbsolutePath(absolutePath, filename);
		directories.push({
			basename: filename,
			absolutePath: absolutePath,
			id: id,
		});
	}

	workspaceDirectories = directories;

	//if (!languageServer) {
	//	MAIN_initializeLanguageServer();
	//}

	return {
		workspaceFileAbsolutePath: openedWorkspace,
		workspaceFileNameWithoutExtension: path.parse(openedWorkspace).name,
		directories: directories,
		canceled: result.canceled
	};
}

/**
 * Extracts more data per entry { basename, absolutePath, isDirectory, id }
 * and applies a common sorting prior to returning results.
 * */
function wrap_readdirSync_getChildList(parentAbsolutePath: string) {
	// TODO: You solved this when you first made the repo look at the git history... using any I think is wrong.
	let childList: (fs.Dirent<string> | any)[];
	childList = fs.readdirSync(parentAbsolutePath, { withFileTypes: true });
	for (var i = 0; i < childList.length; i++) {
		let filename = childList[i].name;
		let isDirectory = childList[i].isDirectory();
		let childAbsolutePath = path.join(parentAbsolutePath, filename);
		let id = database.addAbsolutePath(childAbsolutePath, filename);
		childList[i] = {
			basename: filename,
			absolutePath: childAbsolutePath,
			isDirectory: isDirectory,
			id: id
		};
	}

	childList.sort((a, b) => {
		if (a.isDirectory && !b.isDirectory) {
			return -1;
		}

		if (!a.isDirectory && b.isDirectory) {
			return 1;
		}

		return a.basename.localeCompare(b.basename);
	});

	return childList;
}

async function getFilesystemEntries(event: any, argument: number | string, argumentIsId: boolean) {

	let parentAbsolutePath;

	if (argumentIsId) {
		let entry = database.getBy_id(argument as number);
		if (!entry) return;

		parentAbsolutePath = entry.value;
	}
	else {
		parentAbsolutePath = argument as string;
		if (!isValidAbsolutePath(parentAbsolutePath)) return;
	}

	try {
		return wrap_readdirSync_getChildList(parentAbsolutePath);
	}
	catch (err) {
		console.error("Error reading directory:", err);
		return [];
	}
}

async function getFilesystemEntryById(event: any, id: number) {
	try {
		let entry = database.getBy_id(id);
		if (!entry) {
			return null;
		}
		else {
			return {
				basename: entry.displayName,
				absolutePath: entry.value,
				isDirectory: fs.statSync(entry.value)?.isDirectory() ?? false
			};
		}
	}
	catch (err) {
		console.error("Error during get-filesystem-entry-by-id:", err);
		return {
			basename: null,
			absolutePath: null,
			isDirectory: false
		};
	}
}

async function getFilesystemEntryById_ARRAY(event: any, arrayKeys: number[]) {
	try {
		const KEY_BITS = 12;
        const KEY_MASK = (1 << KEY_BITS) - 1; // Binary: 00000000000000000000111111111111 (0xFFF)

		let arrayEntries = new Array(arrayKeys.length);
		for (let i = 0; i < arrayKeys.length; i++) {
			let packedInteger = arrayKeys[i];
			const key = packedInteger & KEY_MASK;
			let entry = database.getBy_id(key);
			if (!entry) {
				//arrayEntries[i] = null;
				arrayEntries[i] =  {
					basename: 'basenameUndefined',
					absolutePath: 'absolutePathUndefined',
					// TODO: return 'null' not 'true'. And then the UI should interpret this as "whatever you currently have just keep it that way cause nobody knows what the file even is anymore"...
					// ...because presumably a render happened between the time that the FS deleted the file, but before the UI removed it from the node list... this is only speculation but it probably is what is happening.
					// thus the next render should correctly remove the node from the UI anyways.					
					isDirectory: true//fs.statSync(entry.value)?.isDirectory() ?? false
				};
			}
			else {

				let fsStatSyncResult;
				
				try {
					fsStatSyncResult = fs.statSync(entry.value);
				}
				catch (err) {
					fsStatSyncResult = null;
				}

				// Oddly if the node is expanded this works entirely but if collapsed the node visually never gets removed.

				arrayEntries[i] =  {
					basename: entry.displayName,
					absolutePath: entry.value,
					// TODO: return 'null' not 'true'. And then the UI should interpret this as "whatever you currently have just keep it that way cause nobody knows what the file even is anymore"...
					// ...because presumably a render happened between the time that the FS deleted the file, but before the UI removed it from the node list... this is only speculation but it probably is what is happening.
					// thus the next render should correctly remove the node from the UI anyways.
					isDirectory: fsStatSyncResult?.isDirectory() ?? true
				};
			}
		}
		return arrayEntries;
	}
	catch (err) {
		console.error("Error during get-filesystem-entry-by-id:", err);
		return [];
	}
}

type hasBOM_result = {
    text: string,
    fileStartsWithBom: boolean,
    formattedAbsolutePath?: string,
    extension?: string,
};

/**
 * started off with code snippet from Google AI Overview for "node fs determine if file has bom":
 */
function hasBOM(filePath: string): hasBOM_result {
	// Use a small buffer to read just the first 3-4 bytes
	const buffer = Buffer.alloc(4);
	const fd = fs.openSync(filePath, 'r');
	fs.readSync(fd, buffer, 0, 4, 0);

	let stat = fs.statSync(filePath);

	// Check for common BOM signatures
	// UTF-8: EF BB BF
	if (buffer[0] === 0xEF && buffer[1] === 0xBB && buffer[2] === 0xBF) {
		const bufferaaa = Buffer.alloc(stat.size - 4);
		fs.readSync(fd, bufferaaa, 0, bufferaaa.length, 3);
		fs.closeSync(fd);
		return {
			text: bufferaaa.toString(),
			fileStartsWithBom: true
		};
	}
	else {
		const bufferaaa = Buffer.alloc(stat.size);
		fs.readSync(fd, bufferaaa, 0, bufferaaa.length, 0);
		fs.closeSync(fd);
		return {
			text: bufferaaa.toString(),
			fileStartsWithBom: false
		};
	}

	/*
	// UTF-16 Little Endian: FF FE
	if (buffer[0] === 0xFF && buffer[1] === 0xFE) {
		return 'UTF-16LE';
	}
	// UTF-16 Big Endian: FE FF
	if (buffer[0] === 0xFE && buffer[1] === 0xFF) {
		return 'UTF-16BE';
	}
	*/
}

async function editorReadAllText(event: any, absolutePath: string) {
	if(!isValidAbsolutePath(absolutePath)) return;

	try {
		let basename = path.basename(absolutePath);
		let extension = path.extname(absolutePath);

		let itHasBom = hasBOM(absolutePath);

		absolutePath = formatAbsolutePath(absolutePath);
		itHasBom.formattedAbsolutePath = absolutePath;
		itHasBom.extension = extension;

		let pathId = database.addAbsolutePath(itHasBom.formattedAbsolutePath, basename);

		//if (openedDocumentUri) {
		//	let tdIdentifier = lspTypes.MAIN_message_construct_textDocumentIdentifier(absolutePath);
		//	if (languageServerHandshakeSuccess && languageServer) {
		//		languageServer.stdin.write(
		//			MAIN_encodeMessageObject(lspTypes.MAIN_message_construct_didCloseTextDocumentNotification(tdIdentifier)));
		//	}
		//	openedDocumentUri = null; // Should be set null regardless of language server existence to ensure it gets cleared if language server was running then stopped
		//}
//
		//let tdi = lspTypes.MAIN_message_construct_textDocumentItem(
		//	absolutePath,   // uri
		//	'javascript',   // languageId
		//	0,              // version
		//	itHasBom.text); // text
		//let messageObject = lspTypes.MAIN_message_construct_didOpenTextDocumentNotification(tdi);
		//let messageJson = MAIN_encodeMessageObject(messageObject);
		//if (languageServerHandshakeSuccess && languageServer) {
		//	languageServer.stdin.write(messageJson);
		//	openedDocumentUri = absolutePath;
//
		//	// TODO: Somewhat nonsensical to check 'openedDocumentUri' but I'm not sure if it was ever validated and I don't wanna deal with it right now...
		//	// ...
		//	// More so, I don't want this new logic to ever have a possibility of crashing the old logic (which simply wanted to read the text.)
		//	// So until I guarantee that 'openedDocumentUri' is validated, I don't want to take any risks with it. (and maybe it is validated I just don't know either which way)
		//	//
		//	if (openedDocumentUri) {
		//		let tdIdentifier = lspTypes.MAIN_message_construct_textDocumentIdentifier(openedDocumentUri);
		//		let customFullFileLexRequest = lspTypes.MAIN_message_construct_CustomFullFileLexRequest(tdIdentifier);
		//		mostRecentRequest = customFullFileLexRequest;
		//		languageServer.stdin.write(MAIN_encodeMessageObject(customFullFileLexRequest));
		//	}
		//}
		
		return itHasBom;
	}
	catch (err) {
		return null;
	}
}
